---
title: "R Notebook"
output: html_notebook
---

```{r}
library(psych)
library(reshape2)
library(ggplot2)

IASData <- read.csv(file="IASDataset.csv")
```


```{r}
dim(IASData)
head(IASData)
summary(IASData)
names(IASData)
cor(IASData[,c(1:13)])

# make heatmap
cormat <- round(cor(IASData[,c(1:13)]),2)

melted_cormat <- melt(cormat)
head(melted_cormat)

ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()

```

```{r}
#factor estimation
EigenDecomp <- eigen(cov(IASData[,c(1:13)]))
EigenValues <- EigenDecomp$values
plot(EigenValues,main="Scree Plot IAS",type="l",xlab="Number of Factors",ylab="Eigen Values")
```

```{r}
# 2: Estimate the factors using maximum likelihood
k<-2
EFA.kfactors <- factanal(IASData[,1:13], factors=k,
rotation="none")
EFA.kfactors$converged

# variables with a uniqueness > 0.8 are dropped from the analysis.
EFA.kfactors 
```

```{r}
# Define number of factors sequence:
NrFactors <- 1:5
# Reserve space for p-values in memory, by creating an empty
# vector with Non-Availables (NA) of the same length as NrFactors:
pvals <- rep(NA,times=length(NrFactors))
for(k in NrFactors){
# Estimate k-factor model:
Estimation <- factanal(IASData[,1:13],factors=k,rotation="none")
pvals[k] <- Estimation$PVAL
}
# Evaluate pvals and convergence for NrFactors:
cbind(NrFactors,pvals)

# choose four factors and test convergence
EFA.kfactors <- factanal(IASData[,1:13], factors=2,rotation="varimax")
EFA.kfactors$converged
EFA.kfactors
```

```{r}
print(EFA.kfactors, digits=2, cutoff=.2)
```

```{r}

# 1: Compute the Cronbach’s alpha for the TimeEscalation factor
CalphaTimeEscalation <- psych::alpha(IASData[,c(1,2,3,5,10,11,13)])
CalphaTimeEscalation
```
```{r}

CalphaTimeEscalation <- psych::alpha(IASData[,c(4, 6, 7, 8, 9, 12)])
CalphaTimeEscalation
```
```{r}
# Create an artificial data.frame for illustration:
Data <- data.frame(IASData)
# Identify the number of observations in Data:
N <- dim(Data)[1]
# Create a random index vector:
shuffle.index <- sample(1:N,size=N/2)
# Shuffle the data:
IASData.Partition1 <- Data[shuffle.index,]
IASData.Partition2 <- Data[-shuffle.index,]


# choose four factors and test convergence
EFA.kfactors <- factanal(IASData.Partition1[,1:13], factors=2,rotation="varimax")
EFA.kfactors$converged
EFA.kfactors

# choose four factors and test convergence
EFA.kfactors <- factanal(IASData.Partition2[,1:13], factors=2,rotation="varimax")
EFA.kfactors$converged
EFA.kfactors
```

```{r}
# 1: Compute factor scores
EFA.2factors <- factanal(IASData[,1:13], factors=2,
rotation="varimax", scores="regression")
FactorScores <- data.frame(EFA.2factors$scores)

IASData$TimeEscalation <- FactorScores$Factor1
IASData$NegativeEffects <- FactorScores$Factor2

plot(IASData$TimeEscalation,IASData$NegativeEffects)
boxplot(IASData$TimeEscalation ~ IASData$gender)
t.test(IASData$TimeEscalation ~ IASData$gender)
boxplot(IASData$NegativeEffects~IASData$gender)
t.test(IASData$NegativeEffects ~ IASData$gender)
```

